### ISSUE TITLE
Модуль не совместим со сторонними модулями

### ISSUE THREAD

**Issue by daniluk4000** [VKCOM/vk-connect#19]
В кастомный плагин для VKConnect, написанный на Typescript, попытался импортировать тип VKConnect. Typescript не увидел модуль package.json, а также расширение global.d.ts. 

Примеры ошибок: 

- Property 'webkit' does not exist on type 'Window & typeof globalThis'.
- Cannot find module '../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

**Comment by danakt** [comment]
Покажите пример использования в вашем проекте, мне кажется вы что-то делаете не так.
 
> Cannot find module '../package.json'.
Данная ошибка не может появляться, потому что в бандле никаких импортов нет

**Comment by daniluk4000** [comment]
Прошу прощения. Я действительно импортировал не оттуда, откуда нужно. IDE не заметила, что тип VKConnect есть в самом `@vkontakte/vk-connect`, и я импортнул из src/. 

Ваш комментарий про dist навел меня на мысль переиндексировать проект, и IDE увидела, что все же тип VKConnect импортируется без таких костылей.

**Comment by danakt** [comment]
Понял! Спасибо за ишью, папка `src` будет удалена из пакета :)
