### ISSUE TITLE
Добавить события VKWebAppDisableSwipeBack и VKWebAppEnableSwipeBack

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/vk-connect#21]
В vk-connect-promise присутствовали события VKWebAppDisableSwipeBack и VKWebAppEnableSwipeBack, так как он сейчас Depricated было бы не лишним добавить их в эту библиотеку.

**Comment by danakt** [comment]
Спасибо за ишью! Добавил методы в типизацию. По сути данные методы можно было использовать, но без тайпингов
