### ISSUE TITLE
Неверная структура ответа VKWebAppOpenPayForm

### ISSUE THREAD

**Issue by nbarinov** [VKCOM/vk-connect#23]
При вызове события VKWebAppOpenPayForm через sendPromise возвращается разные структуры результата на iOS и Android. На Android результат оборачивается ещё в объект result.
![IMG_0353](https://user-images.githubusercontent.com/12908670/68205110-e0c1cd80-ffe2-11e9-8fc5-ca1528765a80.PNG)

![W3UBZX4sbWY](https://user-images.githubusercontent.com/12908670/68205151-f9ca7e80-ffe2-11e9-9486-1fd2982575da.jpg)
<img width="549" alt="image" src="https://user-images.githubusercontent.com/12908670/68205260-4615be80-ffe3-11e9-929c-251fa9ff6c1b.png">

**Comment by danakt** [comment]
Спасибо большое за сообщение! В дальнейшем это исправится на платформе android, однако на текущий момент это исправить нельзя, поскольку неизвестно сколько приложений на этом завязано. 

Пока что в vk-connect будут обновлены типы и будет пофикшен метод в vk-mini-apps-api.

**Comment by nbarinov** [comment]
@danakt спасибо, ждём!
