### ISSUE TITLE
Двойная вложенность 

### ISSUE THREAD

**Issue by nbarinov** [VKCOM/vk-connect#27]
Приветствую!

При вызове метода API в response приходит ещё один response, в котором уже лежит результат. Хотелось бы, чтобы в response уже лежал результат. Пример кода и результат ниже.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/12908670/70182787-fa4b5780-16fd-11ea-88d9-475012dd440a.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/12908670/70182821-0a633700-16fe-11ea-9ec8-b6138020501a.png">

**Comment by danakt** [comment]
@nbarinov спасибо за issue! Данный вид результата вполне обоснован, поскольку в корневом объекте лежит результат запроса VK Connect, а в поле `response` находится уже результат метода API. К примеру, если в будущем понадобится возвращать какую-либо дополнительную информацию непосредственно от VKConnect, то будет неправильно мешать её с результатом метода API

**Comment by nbarinov** [comment]
@danakt да, тогда в этом есть смысл. Спасибо за ответ!
