### ISSUE TITLE
Некорректный тип ответа на запрос VKWebAppGetGeodata на разных платформах

### ISSUE THREAD

**Issue by nbarinov** [VKCOM/vk-connect#30]
Здравствуйте!

При вызове события **VKWebAppGetGeodata** приходит **available** с некорректным типом. На iOS available приходит как Number (1|0), на Android – Boolean (true|false).

<img width="487" alt="image" src="https://user-images.githubusercontent.com/12908670/71114637-9fc7f600-21e9-11ea-8fe7-dc46579592f6.png">

_Пример запроса_

![ios](https://user-images.githubusercontent.com/12908670/71114761-ed446300-21e9-11ea-8db6-409b38d1b4f8.png)
_Результат ответа на iOS_

![android](https://user-images.githubusercontent.com/12908670/71114795-fd5c4280-21e9-11ea-94f6-fa57024b6aa8.png)
_Результат ответа на Android_

**Comment by danakt** [comment]
@nbarinov спасибо за issue! К сожалению, по историческим причинам сейчас это работает так, но в будущем мы придём к общему виду. Я уже обновил тайпинги метода, чтобы поддерживать оба варианта в ts. Если вам для работы принципиален единый результат на разных устройствах, то вы можете попробовать **vk-mini-apps-api**: https://github.com/VKCOM/vk-mini-apps-api/blob/master/src/index.ts#L224
