### ISSUE TITLE
Легально ли использовать includes без полифила?

### ISSUE THREAD

**Issue by stels-cs** [VKCOM/vk-connect#36]
https://github.com/VKCOM/vk-connect/blob/2cf4f3283acef956b3d8ff8b2d2a2bef9ccdbfc5/src/index.ts#L221

В этой строке используется метод Array.includes, судя по всему он остается в таком же виде в js-коде. Из-за чего получаем ошибку на старых андроидах.

![image](https://user-images.githubusercontent.com/8437497/72268381-c46d8d00-3632-11ea-8dfb-c3956be56c8a.png)

**Comment by danakt** [comment]
Резонно, спасибо
