### ISSUE TITLE
Некорректно работают useState с connect.subscribe в useEffect

### ISSUE THREAD

**Issue by WinZip17** [VKCOM/vk-connect#42]
При получении события  в connect.subscribe константы которые были определенны через useEffect отображаются со значением инициализации.
Суть проблемы можно посмотреть тут:
https://github.com/WinZip17/test-vk-app
При включении приложение получает данные пользователя в переменную fetchedUser.
Введенное в поле значение сохраняется в переменную message.
При нажатии на единственную кнопку вызывается метод (формальный, для теста, без требований) connect.send("VKWebAppGetClientVersion", {});
Попадая в connect.subscribe на строки 24-26 видно, что данные приходят правильно, но переменные message и fetchedUser имеют актуальное на момент инициализации значение (null и "") не смотря на то, что они уже менялись.
Вариант через промисы .then, к сожалению, работает не со всеми методами. (например через connect не сработал "method": "wall.get", но сработал устаревим методом @vkontakte/vk-connect-promise)

**Comment by danakt** [comment]
Ваша проблема не связана с поведением `vk-connect`, вы неверно используете `useEffect`.  Прочитайте про зависимости `useEffect`: https://ru.reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect
